name: BikeDashcamAI
options:
  bundleIdPrefix: com.bikedashcam
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  BikeDashcamAI:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: BikeDashcamAI/Sources
      - path: BikeDashcamAI/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bikedashcam.ai
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: YES
    info:
      path: BikeDashcamAI/Resources/Info.plist
      properties:
        CFBundleName: BikeDashcamAI
        CFBundleDisplayName: BikeDashcam AI
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "BikeDashcam需要使用相机来录制骑行视频"
        NSPhotoLibraryAddUsageDescription: "BikeDashcam需要保存录制的视频到相册"
