name: "timesformer"
platform: "onnxruntime_onnx"
max_batch_size: 4

input [
  {
    name: "pixel_values"
    data_type: TYPE_FP32
    dims: [ 16, 3, 224, 224 ]
  }
]

output [
  {
    name: "pooler_output"
    data_type: TYPE_FP32
    dims: [ 768 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: [ 0 ]
  }
]

dynamic_batching {
  max_queue_delay_microseconds: 200
}

optimization {
  execution_accelerators {
    gpu_execution_accelerator : [
      {
        name : "tensorrt"
        parameters { key: "precision_mode" value: "FP16" }
      }
    ]
  }
}
