name: "fusion"
platform: "onnxruntime_onnx"
max_batch_size: 4

input [
  {
    name: "siglip_features"
    data_type: TYPE_FP32
    dims: [ 16, 768 ]
  },
  {
    name: "timesformer_features"
    data_type: TYPE_FP32
    dims: [ 16, 768 ]
  }
]

output [
  {
    name: "global_feature"
    data_type: TYPE_FP32
    dims: [ 512 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: [ 0 ]
  }
]

optimization {
  execution_accelerators {
    gpu_execution_accelerator : [
      {
        name : "tensorrt"
        parameters { key: "precision_mode" value: "FP16" }
      }
    ]
  }
}
